# نام Workflow که در تب Actions گیت‌هاب نمایش داده می‌شود
name: .NET Build and Test

# تعریف زمان اجرای خودکار Workflow
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    # این کار بر روی یک ماشین مجازی با سیستم‌عامل اوبونتو اجرا خواهد شد
    runs-on: ubuntu-latest

    steps:
    # مرحله ۱: دانلود کد پروژه از ریپازیتوری
    - name: Checkout repository
      uses: actions/checkout@v3

    # مرحله ۲: نصب نسخه ۸ دات‌نت بر روی ماشین مجازی
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # مرحله ۳ (اصلاح شده): بازیابی پکیج‌ها با مشخص کردن مستقیم فایل Solution
    # چون Workflow از ریشه پروژه (جایی که .sln هست) اجرا می‌شود، فقط نام فایل کافیست.
    - name: Restore dependencies
      run: dotnet restore BuildingManager.API.sln

    # مرحله ۴ (اصلاح شده): بیلد کردن کل Solution
    - name: Build
      run: dotnet build BuildingManager.API.sln --no-restore

    # مرحله ۵ (اصلاح شده): اجرای تمام پروژه‌های تست در Solution
    - name: Test
      run: dotnet test BuildingManager.API.sln --no-build --verbosity normal
